language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
  - bower_components

deploy:
  - provider:
    access_key_id:
      secure:
    secret_access_key:
      secure:
    bucket: 
    region: eu-central-1
    local_dir: build
    skip_cleanup: true
    on:
      branch: master
